### ISSUE TITLE
Printer and construction lines icons are bigger than their cells in Layer List

### ISSUE THREAD

**Issue by xanderdin** [LibreCAD/LibreCAD#1021]
This issue is obviously created by the fix https://github.com/LibreCAD/LibreCAD/commit/8d8c154552be592960259f570484c32734f3f73a for the https://github.com/LibreCAD/LibreCAD/issues/980 issue.

Currently it looks like this:

![2](https://user-images.githubusercontent.com/14307537/46914342-35437680-cfa4-11e8-8cf4-352b1d1e6de5.png)

Before the fix it was looking like this:

![1](https://user-images.githubusercontent.com/14307537/46914341-34aae000-cfa4-11e8-9cb4-52714f3646f0.png)

Version: 2.2.0-rc1-50-gd90dbd2b
Compiler: GNU GCC 6.3.0
Compiled on: Oct 14 2018
Qt Version: 5.7.1
Boost Version: 1.62.0
System: Debian GNU/Linux 9 (stretch)
MATE Desktop Environment 1.16.2

**Comment by lordofbikes** [comment]
It's correct, the icons was adjusted, because they looked smaller before, on my system. Now it's ok for me.
![librecadlayerlisticons](https://user-images.githubusercontent.com/386273/46917286-9cbdee00-cfc5-11e8-962c-455e1f8256bb.png)

The difference in build environments is GCC 6.3 vs. 7.3 and Qt 5.7.1 vs. 5.9.5, Boost shouldn't matter.
I suspect Qt, but because the freeze and lock icons are fine on both systems, we have to check the icon creation process.
Another possible cause is display resolution, I use UHD display with 150DPI setting in Ubuntu 18.04.
What is your display size?

**Comment by lordofbikes** [comment]
If this fix doesn't work for you, please report and we will reopen the ticket.

**Comment by xanderdin** [comment]
It works. Thank you very much!

**Comment by lordofbikes** [comment]
Glad to hear this. Many thanks for reporting! :+1:
