### ISSUE TITLE
After modifying layers program crashes

### ISSUE THREAD

**Issue by Newcastleslyfox** [LibreCAD/LibreCAD#1214]
After zooming in/out a lot or making construction line layers visible again the program locks up and requires a forced shutdown of the program. Bug appears to be itermittent.

Program crash/locks up and need to force quit to restart program

Refer to the attached file

Mac OS 10.15.4 and Libre CAD 2.1.3

[Git DXF.zip](https://github.com/LibreCAD/LibreCAD/files/4465665/Git.DXF.zip)

**Comment by lordofbikes** [comment]
This has the same cause as #979 which is solved since Mar. 2018
Sadly the latest DMG package is from Feb. 2018 and still has this issue.
Iirc this is caused by non continuous construction lines.
So you can avoid construction layers or use only solid lines in construction layers as work around.
Thanks for reporting anyhow and bringing this back to attention.
