### ISSUE TITLE
Options for Relative zero position

### ISSUE THREAD

**Issue by TonyWhite** [LibreCAD/LibreCAD#1393]
### Expected behavior
I would like to have an option for:
- Show / hide the relative zero position
- Change color to relative zero position

### Operating System and LibreCAD version info
Version: 2.1.3 from Debian Stable repos.

**Comment by melwyncarlo** [comment]
Should it be implemented in settings, or as toolbar buttons?

**Comment by fa201** [comment]
I suggest settings, it will take less room on the main window.

**Comment by melwyncarlo** [comment]
Okay, and do I just do the coordinate position, or the angles as well?

If both, then do I implement separate options for each of them, 
or do I apply the same settings for both of them?

**Comment by fa201** [comment]
I suggest the coordinate position.

**Comment by lordofbikes** [comment]
To avoid any misunderstandings:
- In first place this issue is about hiding the red crossed circle in the drawing area
- And also about an option to change the color of this marker

Both should be located in *Application Preferences* where we have already similar setting, e.g. for the snap indicator.

What @melwyncarlo mentioned is the relative position widget in the statusbar, which becomes useless when the relative zero marker is disabled. So this should optional be hidden too.

And there are also two tool buttons in the *Snap Selection* tool bar, concerning the relative zero marker (set and lock), which become useless.
These buttons could also be added to user defined tool bars. So they should be found too and then hidden or at least disabled.

I haven't found these actions in the menus, but maybe I overlooked them?

Last but maybe not least is the command line. When the relative zero marker is disabled, using relative coordinates with `@` can create random result. Any thoughts?

**Comment by melwyncarlo** [comment]
@lordofbikes I couldn't find them in the menus either.

And what do you mean by user-defined toolbars? I couldn't understand. The two buttons are present in the _Snap Selection_ tool bar as well as in the _Toolbar Creator_ options.

<hr>

I can confirm the error. I'll solve the relative coordinates error as a separate pull-request.

<hr>

Regarding @TonyWhite's query, you need options to show/hide and change colour of the red circular relative-zero marker, 
and NOT the co-ordinates in the status bar. Am I correct?

Also, upon showing/hiding the marker, you need the program to automatically enable/disable the following:
* relative coordinates in the status bar (hide its text)
* set marker button
* lock marker button

**Comment by TonyWhite** [comment]
@melwyncarlo yes, I'm only interessed to hiding the marker. The relative coordinates are useful.

**Comment by melwyncarlo** [comment]
Done!

Video link :  [https://youtu.be/2VstFRewuiw](https://youtu.be/2VstFRewuiw)

**Comment by TonyWhite** [comment]
@melwyncarlo thanks! This is exactly what I expect!

Now a question to avoid run-time bugs.
When the marker is hidden, it is possible to use and update relative coordinates?

Example:
- Hide the marker
- Start creating line clicking into drawing area
- Create a line with `@0,-10`
- Continue with `@10,0`

The result must be a "L" shape

**Comment by melwyncarlo** [comment]
Yes it is possible!

**Comment by dxli** [comment]
merged 5b541e665
