### ISSUE TITLE
Four essential tools missing from Dock Widgets

### ISSUE THREAD

**Issue by jbergengh** [LibreCAD/LibreCAD#1511]
There are 4 essential Tools that are missing from the Standard Toolbars and Dock Widgets.  They are:

**MText
Text
Hatch
Points**

They are listed under the Tools drop-down menu.  They can be added to a custom Toolbar.
But there is no way to add these Tools to a Dock Widget because they are missing from the Standard Toolbars.

I'm requesting that these four tools be added to the Standard Toolbars so they show up in Dock Widgets

It's somewhat debatable which Toolbar to add each Tool to, but I propose the following:

Add the Points tool to the Line toolbar
Add the MText, Text, and Hatch tools to the Dimension toolbar

Unfortunately, I don't know how to use Git (god knows I've tried), so I'm hoping someone can do this on my behalf.  I've been modifying my source manually (more times than I can count).  The changes are as follows:

Edit **/librecad/src/ui/lc_widgetfactory.cpp**

Add, to the end of the **line_actions** section, **a_map["DrawPoint"]**
Add, to the end of the **dimension_actions** section, **a_map["DrawMText"]**, **a_map["DrawText"]** and **a_map["DrawHatch"]**

The tools can then be removed from the Tools drop-down menu by commenting out:

    tools_menu->addAction(a_map["DrawMText"]);
    tools_menu->addAction(a_map["DrawText"]);
    tools_menu->addAction(a_map["DrawHatch"]);
    tools_menu->addAction(a_map["DrawPoint"]);

I'm including a screenshot of how the LibreCAD DockWidgets look when finished.

Note that **MText** and **Text** use the same icon.  Bonus points may be awarded if this can be fixed as well. :-)

![Tools added to DockWidgets](https://user-images.githubusercontent.com/55407804/149398422-5f3f3765-390b-4fb6-9836-059679f70ba8.png)

**Comment by pollywinters** [comment]
Had a look at this, found several other tools that were also mising from the Standard Toolbars and Dock Widgits:
**Draw Circle Inscribed**
**Draw Circle Concentric**
**Insert Image**
Insert Image could be called via the File/Import menu, but the two circle operations did not seem to be available anywhere except by creating a custom toolbar or menu, where they could be picked from the list of possible actions.

Also it seemed to me a bit clunky that the entity reordering tools, move to top, move to bottom etc are accessed via a sub-sub-menu from the Tools/Modify menu, unlike any other actions.

There were also two entries in the toolbar/menu creators picklist for each of **Show all** and **Hide all**, on inspecting the code these turned out to actually be for show/hide **layers** and show/hide **blocks**, but with identical names and icons it was impossible to distinguish between them in the list.

Lastly I found a **Delete Freehand** operation within the toolbar/menu creators picklist which did not have any icon attached.

My suggested changes for all of these are:

- **MText**, **Text**, **Hatch** and **Points** actions added into the widget sections as suggested by [jbergengh](https://github.com/jbergengh) above.
- **Insert Image** action also added into the Dimensions widget section, providing easy access to this.
- A new icon added for **Mtext** to distinguish it from **Text** as requested by [jbergengh](https://github.com/jbergengh).
- **Draw Circle Inscribed** and **Draw Circle Concentric** actions added into the Circles widget section.
- A new section **Order** added into the Tools menu and the Tools Categories toolbar, to hold the entity reordering tools. The Tools/Modify/Order sub-sub-menu now removed.
- Action names for the show/hide all entries changed to **Show all layers**, **Hide all layers**, **Show all blocks**, **Hide all blocks** so that these actions can be distinguished in the toolbar/menu creators picklist.
- A new icon added for **Delete Freehand**. This action is still not present by default in any of the toolbars or menus, however my experimentation with it seemed to show problems with this operation, possibly it is not yet fully implemented. Anyway there is now an icon ready for use with it.

I have checked all file changes into the pollywinters/LibreCAD fork of the project source and created a pull request #1535 to allow others to experiment with this.
