### ISSUE TITLE
[small feature] Toolbar expansion icon could change to point up (or left to right) after toolbar expands

### ISSUE THREAD

**Issue by leo-smi** [LibreCAD/LibreCAD#1565]
### Expected behavior
The expasion icon could change

### Observed behavior
The expanse icon do not changes

### Steps to reproduce or sample file
1 - Open a blank project
2 - Organize a toolbar in a way that appears a collapse mode
![image](https://user-images.githubusercontent.com/20663547/193428201-5b77f622-7839-464f-bc51-06ae77592446.png)
3 - Click on the expand icon
![image](https://user-images.githubusercontent.com/20663547/193428228-36a6bdc5-cd4d-4142-b854-3177177601df.png)
4 - Observe that the expand icon keeps the same, I suggest the icon to point up **OR CHANGE THE CURRENT ICON FROM LEFT TO RIGHT**
![image](https://user-images.githubusercontent.com/20663547/193428285-a0d4df51-db64-4b7c-b8ce-3baecb42d765.png)

### Operating System and LibreCAD version info
Windows 10 
Version: 2.2.0-rc4
Compiler: GNU GCC 12.1.0
Compiled on: Jun  7 2022
Qt Version: 5.12.11
Boost Version: 1.75.0

**Comment by lordofbikes** [comment]
I marked this as `os specific`, because my Linux version does not have these marks at all.

This is either an os specific feature of the Qt framework or of Windows itself.
Widget decoration is in the responsibility of the operating systems window management, this little mark is not actively controlled by LibreCAD code.
