### ISSUE TITLE
"Snap to middle" and "Snap to Endpoints" reacts very strangely to the lines on the "construction" layer

### ISSUE THREAD

**Issue by MikePryadko** [LibreCAD/LibreCAD#1566]
```
Version: 2.1.3
Compiler: GNU GCC 11.2.0
Compiled on: Jan 30 2022
Qt Version: 5.15.3
Boost Version: 1.74.0
System: Ubuntu 22.04.1 LTS
```
This is some demonstration:

https://user-images.githubusercontent.com/31248040/195336405-d3de287d-2dc8-47ea-8fee-e1b968055e7b.mp4

IMHO Lines on "construction" layer are **endless** so "snap to middle" must not work with it.

---

**UPD:** "Snap to Endpoints" have same "strange" behavior. Perhaps other "snaps" are also affected - I didn't check.

https://user-images.githubusercontent.com/31248040/195340885-b44d2ca2-54cc-4e57-8d76-e49e0c6a35a6.mp4

**Comment by lordofbikes** [comment]
Without inspecting the source code, but some own tests, I see no issue which should be fixed yet.

A construction layer, as its name already says, is for construction. Even when the lines are infinite, they are only extensions of the underlying lines. This should help to find imaginary intersections or to align entities correctly.

The Snap tools react to the underlying lines, which explains the snap points with mentioned Snap functions. The various snap points with Snap to Middle function are multiples of the underlying lines middle distance. But this seems to work only in positive direction, as it only works behind the end of the line but not in reverse direction.

So the conclusion would be, that using most Snap functions on construction layers is senseless, because infinite lines don't have start, end or middle points.
But with a thought-out base of lines for a construction layer, the Snap functions can be very useful.

So I would not change this yet, as I'm sure that there are users out there, who are happy with current behavior.
