### ISSUE TITLE
New Functionality - LAYER PANEL - Duplicate Layer / Copy Layer

### ISSUE THREAD

**Issue by Didier-H** [LibreCAD/LibreCAD#1665]
### Expected behavior

While in the LAYER PANEL -> Duplicate Layer

- Go to a dialog where you can give the future new layer a new name, based on the current one
- With OK Button Create a new layer with the same properties of the previous one (color, size, line type), WITHOUT THE CONTENT (lines attached to the layer)

While in the LAYER PANEL -> Copy Layer

- Go to a dialog where you can give the future new layer a new name, based on the current one
- With OK Button Create a new layer with the same properties of the previous one (color, size, line type), WITH THE CONTENT (lines attached to the layer)

### Operating System and LibreCAD version info

Version: 2.2.0-rc3-24-g4602ec6a
Compiler: GNU GCC 7.3.0
Compiled on: Mar  5 2022
Qt Version: 5.12.4
Boost Version: 1.65.1
System: Windows 10 (10.0)

**Comment by sand1024** [comment]
this is addressed there - https://github.com/LibreCAD/LibreCAD/issues/1731

**Comment by Didier-H** [comment]
Thank you for this news

But I did donwload latest version 2.2.0.2, and I cannot find the "Layer tree Widget" anywhere.

How to proceed to have a version with this new functionality ?

Thank you

@Bientôt, Didier
________________________________
De : sand1024 ***@***.***>
Envoyé : samedi 3 février 2024 14:50
À : LibreCAD/LibreCAD ***@***.***>
Cc : Didier-H ***@***.***>; Author ***@***.***>
Objet : Re: [LibreCAD/LibreCAD] New Functionality - LAYER PANEL - Duplicate Layer / Copy Layer (Issue #1665)


this is addressed there - #1731<https://github.com/LibreCAD/LibreCAD/issues/1731>

**Comment by lordofbikes** [comment]
This is just work in progress and not available in official downloads yet.
@sand1024 you should not promote it this way to avoid this kind of irritations.

**Comment by sand1024** [comment]
yes, this is not part of official codebase nor release so far - sorry for the confusion. Of course, I can create a pull request yet anyway, it's necessary to wait until/if it will be merged into main codebase and when new version will be released. 

So right now I'm aftraid the only way to test that feature - is to build it from sources

**Comment by Didier-H** [comment]
Hi there.

I am not at a level to be able to compile anything from the code base.

It is effectively frustrating not to have access really to that wonderful functionality, even more as I need it right now for a new xork in progress.

But it is nice so far too to know that a bright new functionality exist somewhere somehow.

Hope it will be merge in an available version ASAP;

@Bientôt, Didier
________________________________
De : sand1024 ***@***.***>
Envoyé : samedi 10 février 2024 22:21
À : LibreCAD/LibreCAD ***@***.***>
Cc : Didier-H ***@***.***>; Author ***@***.***>
Objet : Re: [LibreCAD/LibreCAD] New Functionality - LAYER PANEL - Duplicate Layer / Copy Layer (Issue #1665)


yes, this is not part of official codebase nor release so far - sorry for the confusion. Of course, I can create a pull request yet anyway, it's necessary to wait until/if it will be merged into main codebase and when new version will be released.

So right now I'm aftraid the only way to test that feature - is to build it from sources

**Comment by sand1024** [comment]
well, just for testing purposes, I've created a custom build with this feature enabled (as far as I understand, you're on windows?). 

As far as I understand, you need this feature earlier than it will be tested and integrated into main version, so that's why I've created such a shortcut. 

I don't now what is the proper way of sharing such builds, so I've uploaded it into my Google Drive, the link is there https://drive.google.com/file/d/1ewS02vmgPdMyrbje-9mCfeS2MAQqzlWb/view?usp=drive_link

Just unpack the content of the archive with restoring directory structure into some separate directory and try to run exe file from there.  It might be that some plugins (like plot equation will not load, however). 

Of course, this is development snapshot version which is not fully tested - therefore it might be that some crashes or errors will occur. 
In general, I don't think that your drawings may be corrupted, yet please use this version on your own risk and for sure make a backups frequently. 

If you'll find any bug or will see some room for improvements, just please report them there https://github.com/sand1024/LibreCAD/issues - as this code is not merged into master yet, I think it's not practical to report something in main repo.  Ideally, if you'll also attach the dxf file itself (that's fine if it will be without entities, what is more important for testing this feature is the list of layers that should be present in dxf). 

If there are some better way how it is possible to share dev' builds - please let me know.

**Comment by Didier-H** [comment]
Hi Sand1024

Thank you for this work.

But apparently, when I try to access your google drive, it asks me to launch a request access.

I click the button, and normally, I should have received a return email with the agreement, but I did not receive anything.

Sorry for that

@Bientôt, Didier
________________________________
De : sand1024 ***@***.***>
Envoyé : lundi 12 février 2024 09:46
À : LibreCAD/LibreCAD ***@***.***>
Cc : Didier-H ***@***.***>; Author ***@***.***>
Objet : Re: [LibreCAD/LibreCAD] New Functionality - LAYER PANEL - Duplicate Layer / Copy Layer (Issue #1665)


well, just for testing purposes, I've created a custom build with this feature enabled (as far as I understand, you're on windows?).

As far as I understand, you need this feature earlier than it will be tested and integrated into main version, so that's why I've created such a shortcut.

I don't now what is the proper way of sharing such builds, so I've uploaded it into my Google Drive, the link is there https://drive.google.com/file/d/1ewS02vmgPdMyrbje-9mCfeS2MAQqzlWb/view?usp=drive_link

Just unpack the content of the archive with restoring directory structure into some separate directory and try to run exe file from there. It might be that some plugins (like plot equation will not load, however).

Of course, this is development snapshot version which is not fully tested - therefore it might be that some crashes or errors will occur.
In general, I don't think that your drawings may be corrupted, yet please use this version on your own risk and for sure make a backups frequently.

If you'll find any bug or will see some room for improvements, just please report them there https://github.com/sand1024/LibreCAD/issues - as this code is not merged into master yet, I think it's not practical to report something in main repo. Ideally, if you'll also attach the dxf file itself (that's fine if it will be without entities, what is more important for testing this feature is the list of layers that should be present in dxf).

If there are some better way how it is possible to share dev' builds - please let me know.

**Comment by sand1024** [comment]
please try again

**Comment by Didier-H** [comment]
Hi Sand1024 or Andrew I suppose.

I receive another email with an "more" direct access to a zip file.

This one works.

I decompress the ZIP, keep the same directory structure, and run the exe.

It works.

By the way, I see there is in this compilation a new more complete Pen palette widget.
Is there any explanation how it works ?

@Bientôt, Didier
________________________________
De : sand1024 ***@***.***>
Envoyé : lundi 12 février 2024 10:40
À : LibreCAD/LibreCAD ***@***.***>
Cc : Didier-H ***@***.***>; Author ***@***.***>
Objet : Re: [LibreCAD/LibreCAD] New Functionality - LAYER PANEL - Duplicate Layer / Copy Layer (Issue #1665)


please try again

**Comment by sand1024** [comment]
yep, more info is there https://github.com/LibreCAD/LibreCAD/issues/1735 - again, this is not part of the main official branch (I've created these tools for myself and hope they will be incorporated in major release of LibreCAD one day).  
Please note that this is not fully tested version (yet I don't know any known issues so far) - so please use them with caution. 
Of course, if you'll see any issues - please report them as issues and I'll apply a fix.

**Comment by Didier-H** [comment]
Thank you so much

@Bientôt, Didier
________________________________
De : sand1024 ***@***.***>
Envoyé : lundi 12 février 2024 10:55
À : LibreCAD/LibreCAD ***@***.***>
Cc : Didier-H ***@***.***>; Author ***@***.***>
Objet : Re: [LibreCAD/LibreCAD] New Functionality - LAYER PANEL - Duplicate Layer / Copy Layer (Issue #1665)


yep, more info is there #1735<https://github.com/LibreCAD/LibreCAD/issues/1735> - again, this is not part of the main official branch (I've created these tools for myself and hope they will be incorporated in major release of LibreCAD one day).
Please note that this is not fully tested version (yet I don't know any known issues so far) - so please use them with caution.
Of course, if you'll see any issues - please report them as issues and I'll apply a fix.

**Comment by sand1024** [comment]
Thank you for your feedback.  

Well, I use LibreCAD quite often, and actually I like it. 

I simply identified some features that I'd like to have but that are currently missing - so I've decided to add them.   Usually I create lots of layers and its natural to group them based on logical structure of parts - so that was the reason for hierarchical layers (actually, my initial intent was better support of group layers operations, however, during the development I've noticed other features that seems to be useful). 

As for pen palette - usually I use meanful and uniform colors in my drawings (say, per materials, or per purpose (like for axises). And one day I decided that it is quite anoying to specify pen's attributes individually again and again. So I decided to support persistent pens - plus a couple of small yet nice operations. 

As result, the pen palette become quite useful selection tool (based on pen attributes or actual appearance - drawing pen), plus a time saver for me for applying uniform pens. 

Yes, hope that after some testing they will be incorporated into the main branch and so become the part of official release. 

However, If you have some suggestions or features you'd like to see as part of LibreCAD - don't hesitate to let me know, I'll be glad to support them if it will be possible.

**Comment by Didier-H** [comment]
Thank you Andrew (I suppose it is your firstname)

I am using LibreCAD for supporting my drawing of islamic geometry pattern, following the fundamental ancestral approach, I leanerd with my master, Moahamd Aljanabi

We use only a compas, a pen and a straight edge.

We try to reproduce very old pattern found here and there in the world with this ancestral method.
We obviously work a lot by hand, but when it comes to share, or explain to others, the digital era help a lot.

So I use LibreCAD to reproduce all the step, but using only the same tools as the ones used by hands, the line, the arc and the circle.

And like you, I use specific pen parameters, and it is far heavy to have to repeat them often.

Regards from Belgium

@Bientôt, Didier
________________________________
De : sand1024 ***@***.***>
Envoyé : mardi 13 février 2024 16:15
À : LibreCAD/LibreCAD ***@***.***>
Cc : Didier-H ***@***.***>; Author ***@***.***>
Objet : Re: [LibreCAD/LibreCAD] New Functionality - LAYER PANEL - Duplicate Layer / Copy Layer (Issue #1665)


Thank you for your feedback.

Well, I use LibreCAD quite often, and actually I like it.

I simply identified some features that I'd like to have but that are currently missing - so I've decided to add them. Usually I create lots of layers and its natural to group them based on logical structure of parts - so that was the reason for hierarchical layers (actually, my initial intent was better support of group layers operations, however, during the development I've noticed other features that seems to be useful).

As for pen palette - usually I use meanful and uniform colors in my drawings (say, per materials, or per purpose (like for axises). And one day I decided that it is quite anoying to specify pen's attributes individually again and again. So I decided to support persistent pens - plus a couple of small yet nice operations.

As result, the pen palette become quite useful selection tool (based on pen attributes or actual appearance - drawing pen), plus a time saver for me for applying uniform pens.

Yes, hope that after some testing they will be incorporated into the main branch and so become the part of official release.

However, If you have some suggestions or features you'd like to see as part of LibreCAD - don't hesitate to let me know, I'll be glad to support them if it will be possible.

**Comment by Didier-H** [comment]
Hi there.

I am searching for the way to create


  *
Master layer, the one identified with two green cylinders on its left
  *
Child layer, as I cannot find the create child layer entry in the menu as I see in your YouTube demo

Thanks for any help


@Bientôt, Didier
________________________________
De : sand1024 ***@***.***>
Envoyé : samedi 3 février 2024 14:50
À : LibreCAD/LibreCAD ***@***.***>
Cc : Didier-H ***@***.***>; Author ***@***.***>
Objet : Re: [LibreCAD/LibreCAD] New Functionality - LAYER PANEL - Duplicate Layer / Copy Layer (Issue #1665)


this is addressed there - #1731<https://github.com/LibreCAD/LibreCAD/issues/1731>

**Comment by sand1024** [comment]
Hm... in which version do you see such behavior? One I've shared some time ago or latest build?  
Please note that actually there are both "Layer list" original widget and "Layer tree". 

As for drag&drop.. - well, I'll check - can you share the drawing where you see such functionality? If will be more than fine if you make a copy of drawing and remove all entities, yet what is important there for me to check is the list of layers that are part of drawing.

**Comment by Didier-H** [comment]
Hi there.

I try to learn how to use the "Tree List" in the version you have sent.
Here is the About capture

Version: 2.2.0-alpha
Compiler: GNU GCC 7.3.0
Compiled on: Feb 11 2024
Qt Version: 5.14.2
Boost Version: 1.84.0
System: Windows 10 Version 2009

As far as I know, the Layer Tree feature, as well as the pen palette feature are not yet in the last "Official" version 2.2.0.2

For the DragNDrop, I join a link to a short video. Hope you can understand that nothing happens. (or that I am doing something wrong)

[https://res-h3.public.cdn.office.net/assets/mail/file-icon/png/video_16x16.png]2024-04-24 10-39-17_DragNDrop_01.mp4<https://1drv.ms/v/s!Am7lq3lG9KpSi6BqYx-gQmxK6EXjZA>

Anyway, the Create child layer does not appaear anyway.

Thank you for your help

@Bientôt, Didier
________________________________
De : sand1024 ***@***.***>
Envoyé : mardi 23 avril 2024 21:41
À : LibreCAD/LibreCAD ***@***.***>
Cc : Didier-H ***@***.***>; Author ***@***.***>
Objet : Re: [LibreCAD/LibreCAD] New Functionality - LAYER PANEL - Duplicate Layer / Copy Layer (Issue #1665)


Hm... in which version do you see such behavior? One I've shared some time ago or latest build?
Please note that actually there are both "Layer list" original widget and "Layer tree".

As for drag&drop.. - well, I'll check - can you share the drawing where you see such functionality? If will be more than fine if you make a copy of drawing and remove all entities, yet what is important there for me to check is the list of layers that are part of drawing.

**Comment by sand1024** [comment]
Hello! 

Oh, now I see what do you mean - thank you for this. 

Yes, it seems that this is intentional behavior (at least, according to the current implementation). There are several checks that defines which layer changes are allowed. 

Widgets supports several types of layers. Actually, most of them are just normal LibreCAD layers, except that they have a bit different logical meaning: 
* normal (usual layer)
* dimensional (actually, same is normal yet with primary purpose to hold dimensional data) 
* informational (for notes, comments etc.)
* alternative position - useful if the same part may be drawn in several positions. 

While all above are just regular layers, there is also an artificial "Virtual" layer (.  Actually, this is not true layer in sense of LibreCAD - it just a common prefix for several layer names used for layers grouping.  

You may consider "virtual" layer as analog of folder in file system. 

Virtual layers may contains other virtual layers or normal layers. 

Actually, all that layers hierarchy is built based on proper naming of layers (as there is no native support of layers hierarchy in AutoCAD DXF files) - that's why if you'll switch to built-in Layer List widget, you'll see longer layer names with separators. 

While potentially it is possible that normal layer will have another layer as a child - I suppose this is hardly useful and so prohibited this on drag&drop.  I supposes that child layers for normal layer might be only informational, dimensional and alternative position layers.  

I've did this due to the following consideration - if some layer represents some physical part, it may be reasonable that such information related to part is within the same hierarchy. 

As for grouping different parts - I've considered that "virtual" layer will be enough. 

So basically, this is the issue of overall conventions. 

In order to address creation of groups as you've shown on the video - I can suggest you the following approach. 

1) First, please check settings of the widget (gear green icon) - there is a naming convention that is used to create hierarchy). 
What is the most important setting - it's Layer Level Name Separator (default is "-"),  or [SEP] below.

2) Try to create a new layer in form "GropName[SEP]LayerName.  In such case, you should see that virtual layer "GroupName" is created (with green icon) and it contains one normal layer "LayerName" (of course, you can use any names for group and layer name). 

3) Later, you can add other child layers for GroupName  - either via drag&drop, or via right-click context menu on virtual layer item (via "Create Child Layer" command). Please note also other commands available in that menu. 

Thus, so far there is no possibility to create just single virtual layer without any children due to limitations of storage format.  

Of course, it's less convenient to create group layers with their full names, however, by my testing and usage experience, that's seems to be fine. 

In general, I think it will be possible to add separate setting that will let layers hold other layers and enable functionality you've shown in the video. 

Please try the approach I've described, and if it will not work - please let me know. 

Thank you.

**Comment by sand1024** [comment]
Oh, btw - in order to enable group in your video - you can simply rename 
Grp01_SubLayer1 to Grp01-SubLayer1 (if - is layer name separator)

**Comment by Didier-H** [comment]
Hello.

Thank you so much for your detailed reply, which is crystal clear.

I've worked for more than 20 years in IT Tech, it makes things easier to understand.

Waiting for your reply, and making some test, I've detected that layer hierarchy was built based on structured layer name with a dedicated separator. I switch mine to # has often - or _ are used in my layer name.Great point that you have implemented too a parameter screen.

I was only searching how to create "virtual layers".

Based on your explanation, it works perfectly, and the reorganisation with Drag&Drop feature works perfectly as well.

Thanks again for your help.

@Bientôt, Didier
________________________________
De : sand1024 ***@***.***>
Envoyé : mercredi 24 avril 2024 20:12
À : LibreCAD/LibreCAD ***@***.***>
Cc : Didier-H ***@***.***>; Author ***@***.***>
Objet : Re: [LibreCAD/LibreCAD] New Functionality - LAYER PANEL - Duplicate Layer / Copy Layer (Issue #1665)


Hello!

Oh, now I see what do you mean - thank you for this.

Yes, it seems that this is intentional behavior (at least, according to the current implementation). There are several checks that defines which layer changes are allowed.

Widgets supports several types of layers. Actually, most of them are just normal LibreCAD layers, except that they have a bit different logical meaning:

  *   normal (usual layer)
  *   dimensional (actually, same is normal yet with primary purpose to hold dimensional data)
  *   informational (for notes, comments etc.)
  *   alternative position - useful if the same part may be drawn in several positions.

While all above are just regular layers, there is also an artificial "Virtual" layer (. Actually, this is not true layer in sense of LibreCAD - it just a common prefix for several layer names used for layers grouping.

You may consider "virtual" layer as analog of folder in file system.

Virtual layers may contains other virtual layers or normal layers.

Actually, all that layers hierarchy is built based on proper naming of layers (as there is no native support of layers hierarchy in AutoCAD DXF files) - that's why if you'll switch to built-in Layer List widget, you'll see longer layer names with separators.

While potentially it is possible that normal layer will have another layer as a child - I suppose this is hardly useful and so prohibited this on drag&drop. I supposes that child layers for normal layer might be only informational, dimensional and alternative position layers.

I've did this due to the following consideration - if some layer represents some physical part, it may be reasonable that such information related to part is within the same hierarchy.

As for grouping different parts - I've considered that "virtual" layer will be enough.

So basically, this is the issue of overall conventions.

In order to address creation of groups as you've shown on the video - I can suggest you the following approach.

  1.  First, please check settings of the widget (gear green icon) - there is a naming convention that is used to create hierarchy).
What is the most important setting - it's Layer Level Name Separator (default is "-"), or [SEP] below.

  2.  Try to create a new layer in form "GropName[SEP]LayerName. In such case, you should see that virtual layer "GroupName" is created (with green icon) and it contains one normal layer "LayerName" (of course, you can use any names for group and layer name).

  3.  Later, you can add other child layers for GroupName - either via drag&drop, or via right-click context menu on virtual layer item (via "Create Child Layer" command). Please note also other commands available in that menu.

Thus, so far there is no possibility to create just single virtual layer without any children due to limitations of storage format.

Of course, it's less convenient to create group layers with their full names, however, by my testing and usage experience, that's seems to be fine.

In general, I think it will be possible to add separate setting that will let layers hold other layers and enable functionality you've shown in the video.

Please try the approach I've described, and if it will not work - please let me know.

Thank you.
