### ISSUE TITLE
Lua Support

### ISSUE THREAD

**Issue by Questions2000** [LibreCAD/LibreCAD#1801]
Sorry, just a quick question.
I have been informed that LibreCAD 3 is no longer in development.
One of the planned updates for LibreCAD 3 was going to be the support for Lua scripting for tools/plugins.
I was wondering if there are any plans to now add support for Lua in LibreCAD 2 instead?

Thank You

**Comment by dongxuli-concord-design** [comment]
I suppose we can do python instead, but have no idea on how.

**Comment by lordofbikes** [comment]
For quick questions and discussions we prefer the forum https://forum.librecad.org.

In https://github.com/LibreCAD/LibreCAD_3/issues/403#issuecomment-2143353297 I just said, that **currently** nobody is working on V3.

V3 already has LUA, because everything in V3 started with LUA.
To implement a modern scripting language into the mature V2 code base was checked more than once and mostly discarded because of the core concept in V2 not being easy adaptable to available libraries.
