### ISSUE TITLE
Request for Standardization and Clarity in Version

### ISSUE THREAD

**Issue by cdwmhcc** [LibreCAD/LibreCAD#1811]
### Description

Dear LibreCAD Developers,

I have noticed some inconsistencies in the version numbering in the releases section which could potentially confuse users who are trying to track changes or understand the progression of the software releases.

### Examples of Current Version Tagging

Here are a few examples from the Releases page that illustrate the current inconsistency in version naming:

- [2.2.1_rc-latest](https://github.com/LibreCAD/LibreCAD/releases/tag/2.2.1_rc-latest) Pre-release
- [2.2.0-latest](https://github.com/LibreCAD/LibreCAD/releases/tag/2.2.0-latest) Pre-release
- [2.2.2_alpha-latest](https://github.com/LibreCAD/LibreCAD/releases/tag/2.2.2_alpha-latest) Pre-release
- [2.2.0.1](https://github.com/LibreCAD/LibreCAD/releases/tag/2.2.0.1) Latest

It is unclear why versions are tagged with both a semantic versioning system and a 'latest' suffix, or why there is a mix of underscores, periods, and alpha/RC designations in seemingly stable releases.

### Suggestion

I recommend standardizing the version numbering format by adopting [Semantic Versioning (SemVer)](https://semver.org/). This would help clarify release maturity and expected stability/feature set. For example:

- For initial development and testing: `2.2.3-alpha`, `2.2.3-beta`
- Release candidates: `2.2.3-rc.1`, `2.2.3-rc.2`
- Stable releases: `2.2.3`

This format can help both users and developers understand at a glance the stability and newness of each release.

### Conclusion

I hope you will consider this proposal to standardize version numbering. I believe adopting SemVer can significantly streamline development workflows and help both contributors and users to better understand the significance of each release.

Thank you for considering this suggestion, and for your continued dedication to improving LibreCAD.

**Comment by lordofbikes** [comment]
Many thanks for your request.

We already follow SemVer suggestions.

What you criticize are the tags automatically created by continuous integration (CI).
Look at https://github.com/LibreCAD/LibreCAD/tags, where you find all the mentioned tags without `-latest` appendix.

But all those tags mark _Pre Release_ versions. When they were tagged, their assets were named as you suggested. But it does not make sense to keep these assets, when the pre release gets new commits. When commits are added to any branch, its tag is appended with `-latest`.
The assets have there own appendix semantic to help us identify the exact point in source code history.
E.g. the Pre Release labeled `2.2.1_rc2-latest` has an asset `LibreCAD-2.2.1_rc2-11-g933d5378-win64.exe`.

Also the version information in the application's _About_ window is `2.2.1_rc2-11-g933d5378`.
This is basic `git` semantic, which allows us to identify the exact position in history of source code, when the binary was built. It is combined from the version tag `2.2.1_rc1` and the git appendix `-11-g933d5378`, which tells us, that the source code is 11 commits ahead of `2.2.1_rc1` and the commits hash starts with `933d5378`.

There is currently the only stable release `2.2.0.2`. There are a few minor fixes which created the `2.2.0.2-latest` pre release tag.
Then there is the `2.2.1_rc2` release candidate branch, tagged `2.2.1_rc2-latest` because it is ahead of tagged `2.2.1_rc2`.
And the development branch `2.2.2_alpha`, which is considered unstable and tagged `2.2.2_alpha-latest`, because it is ahead of `2.2.2_alpha` tag.
Contributors must understand _Git_ and our workflows with CI and they usually do not struggle with it.

Important for the user is the latest official release `2.2.0.2`, which is linked on the repos main page. All others are pre release, and work in progress, and therefore tagged `-latest`.
We need a way to tag them for CI and this is how we do it.

If users are confused, they usually ask for help in the [forum](https://forum.librecad.org), where they are directed to the version the are looking for.
