### ISSUE TITLE
No snap for target point with scale to point (free) when isotropic is set.

### ISSUE THREAD

**Issue by dellus** [LibreCAD/LibreCAD#1858]
Expected behavior: Snap for target point with scale to point (free) when isotropic is set should be available.

 Observed behavior: No snap for target point is available with scale to point (free) when isotropic is set, works for non isotropic.

Version: 2.2.2_alpha1-143-g466d081d
Compiler: GNU GCC 9.4.0
Compiled on: Aug 25 2024
Qt Version: 6.6.3
Boost Version: 1.71.0
System: fossapup64 9.5
Linux appimage

**Comment by sand1024** [comment]
ok, if I'm correct, it's Modify ->Scale action, and there is no snapping if isotropic mode. 
The question is - in which action state (please check the prompt hint in Mouse Widget on in cmd widget). 
For setting target point - well, it's intentional - actually, in that mode the scale value is determined via position of mouse (actually, the proportion of distances of original reference point and target point) - plus, as mouse may be placed everywhere,  a projection of mouse to the infinite line directed from scale center to reference point. 
So while snapping may be improved a bit there, it still will behave differently - as during setting target point state with isotropic scaling, the action actually tries to determine scale factor... so snap there in some situation may simply have no clear geometric meaning (only the scale rules). 
However, I'll extend the action and will add snap for this case too...
