### ISSUE TITLE
Line grid lines has various glitches between each other

### ISSUE THREAD

**Issue by app4soft** [LibreCAD/LibreCAD#1916]
### Expected behavior

Should not be no issues.

### Observed behavior

There are varios glitches in line grid, where there are grid lines offsets (spaces), see the screenshot and annotations description: 

- `A`, `B` and `C` — in some places of the main window _Grid_ lines has offsets from _Meta Grid_ and _Extebded axis lines_, were in other places of the main window there are no spaces between Grid and Meta Grid lines;
- `D` — both, _Grid_ and _Meta Grid_ lines, has offsets from the edges of the main window, while _Extended axis lines_ has no such an issue.

![Screenshot_2024-10-13_00-45-44](https://github.com/user-attachments/assets/2cc942b9-19d0-46df-9656-2600dec17e15)

### Steps to reproduce or sample file

1. Enable "Line grid" in LibreCAD;
2. Enable "Extend axis lines";
3. Observe Grid, Meta Grid and Extended axis lines.

### Operating System and LibreCAD version info

- Version: 2.2.2_alpha1-180-g8ed4c622
- Compiler: GNU GCC 9.4.0
- Compiled on: Oct 12 2024
- Qt Version: 6.6.3
- Boost Version: 1.71.0
- System: Debian GNU/Linux 12 (bookworm)

**Comment by sand1024** [comment]
well, a small offset of line from metagrid line is intentional (so grid line does not overlap with metagrid line, that's especially important if colors for grid and metagrid are different), if "Simple Grid Rendering" checkbox in Application Preferences->Grid is unchecked. 

Extended lines - they usually overlap metagrid line yet drawn on top of it separately.  

The offset from the end of grid line to metagrid line is calculated as metaGridLineWidthPx * 2 and thus it may be more visible on small screen resolutions. Probably I'll add some setting for multiplying factor above.. 

What is not correct on your screen and looks like a bug, however, is that on A and B areas (top left metagrid tile and top right metagrid tile) there is intersection between grid lines and metagrid lines, I'll check why it's so.
