### ISSUE TITLE
Reordering of Line and Polyline tools

### ISSUE THREAD

**Issue by to-b** [LibreCAD/LibreCAD#319]
In order to improve the usability of LibreCAD non single straight line tools (Rectangles, Polygones1 + 2 and Freehand lines) should be moved away from the Lines menu.
Rectangles, Polygones1 + 2 should create polylines.
See PDF:
http://dl.dropbox.com/u/23492111/ReorderLineAndPolyline.pdf

**Comment by r-a-v-a-s** [comment]
Can anyone think of a benefit to using lines?

What about a tool option to use lines or polylines?

**Comment by atorrey** [comment]
I would tend to think that using lines for anything that can be done in lines as opposed to polylines would be better, as it would give a figure that could be modified easier, since the endpoints of each segment are clearly defined.  

I tend to only want to use a poly-line when there is no simple straight line or curve solution that works....

**Comment by r-a-v-a-s** [comment]
dxli made the rectangle tool produce a polyline: https://github.com/LibreCAD/LibreCAD/commit/d6bbf04b00be9fe7391cf6293af3b0d189a12cdb
:+1:
I think it makes more sense for it to be a single object.
If you move an endpoint, then both associated sides move with it.
If you select a side, then the whole object becomes selected.

**Comment by DuncanLithgow** [comment]
This discussion moved to #320
