### ISSUE TITLE
Feature: UI improvements to tool area

### ISSUE THREAD

**Issue by to-b** [LibreCAD/LibreCAD#320]
Hi,
I have finished my thoughts about another approach to reorganize the tool area.
Like last time most changes are UI related and don't really touch the CAD functionality.
As usual I have prepared a PDF file to make my thoughts clear.
I'm very open to critique... still I hope you like it :)
cheers,
to-b

http://dl.dropbox.com/u/23492111/LibreCAD-Toolbox.pdf

**Comment by r-a-v-a-s** [comment]
We have had a lot of the same ideas.

I agree the delete icon could be removed from the modify menu.
I agree that something like QCad's property editor would be useful.
I agree that some tools could be merged;
however, there is a trade off I'm still weighing...
with tool modes you have added an additional click for switching.

I have created individual toolbars for the categories, and a category toolbar:
![category_toolbar](https://cloud.githubusercontent.com/assets/12013378/9153219/22e504d0-3dfe-11e5-8d25-abb2e510cfb0.png)

I have also created a custom toolbar you can add any action to.
I have been considering a dynamic grid of icons in a dockwidget, which you also thought of;
however, I'm somewhat disenchanted with the idea, because the dockwidgets take up a lot of room.

Another thought just came to me:
1. press a hotkey (maybe ctrl + right-click)
2. the custom toolbar or toolbox appears at the cursor location
3. when a tool is chosen the toolbar is hidden or placed back at its previous position

This with a few other tweaks could allow for a "clean screen" mode 
with all toolbars and menus hidden.

**Comment by atorrey** [comment]
I really dislike hotkeys personally.  No objections to having them present, as long as anything the hotkeys do can still be done via mouse and menus, and ideally if the hotkeys can be turned off...

ART

------------------
Arthur Torrey - <arthur_torrey@comcast.net>
-------------------


----- Original Message -----

**Comment by r-a-v-a-s** [comment]
http://forum.librecad.org/GUI-update-td5712246.html

**Comment by r-a-v-a-s** [comment]
Custom toolbars and menus are more efficient than a dynamic sidebar.
https://github.com/LibreCAD/LibreCAD/wiki/Widgets

We have a separate issue for a properties dockwidget https://github.com/LibreCAD/LibreCAD/issues/622

That leaves the suggestion about a pen dockwidget,
and some tool merging.
Feel free to open issues for those.

I'm closing this because it's too broad,
and a lot has changed since this was opened.
