### ISSUE TITLE
Open file DWG!

### ISSUE THREAD

**Issue by Denisov21** [LibreCAD/LibreCAD#443]
Hello,
I work I would love if this program would open the DWG file!
I'm using this software for both personal and at work. Thank you!

**Comment by Rallaz** [comment]
LibreCAD can now open dwg files

**Comment by kromanenko** [comment]
That`s great!

**Comment by strk** [comment]
How does it open DWG files ? is it using LibreDWG or custom code ?

**Comment by lordofbikes** [comment]
LibreDWG is still not license compatible, we use https://sourceforge.net/projects/libdxfrw/

**Comment by strk** [comment]
Thanks for the hint.

Had you considered relicensing LibreCAD to "GPLv2 or later" ?

**Comment by lordofbikes** [comment]
This is not possible for current version because of GPLv2-only code inherited from the original QCAD.
See this article from 2012, there was no progress:
http://libregraphicsworld.org/blog/entry/libredwg-drama-the-end-or-the-new-beginning

The future [LibreCAD V3](https://github.com/LibreCAD/LibreCAD_3) is GPLv3 or later.

**Comment by strk** [comment]
Thanks! Do you know when's the first LibreCAD V3 release expected ?

**Comment by lordofbikes** [comment]
No, sorry, there is no release plan. Much too less manpower, any help is welcome.
