### ISSUE TITLE
inconsistent inclusion of library files

### ISSUE THREAD

**Issue by r-a-v-a-s** [LibreCAD/LibreCAD#700]
I'm noticing on openSUSE that the library browser contains everything from
https://github.com/LibreCAD/LibreCAD/tree/master/librecad/support/library

On OS X the library browser is empty, and on Windows it's just a couple folders.

The difference is from the postprocess scripts.

What exactly do we want to include?

Would it make more sense to maintain this folder in the Resources repository,
and offer it as an additional download?
That would simplify the postprocess scripts,
and provide a clean library browser for people who would prefer that.
However, it would produce a period of confusion
after the update and when people try to open files that used one of those blocks.

**Comment by fa201** [comment]
Is this still an issue ?

**Comment by lordofbikes** [comment]
This was fixed with 168597a12170b5378ea09c71eb7d5a89afcbcf0f.

Anyhow, we already have https://dokuwiki.librecad.org/doku.php/community:partlibs where additional part libraries are listed for download.

I just created https://dokuwiki.librecad.org/doku.php/community:fonts for additional fonts.
I consider to move some fonts, and possibly some libraries too, to the wiki to reduce the installer package sizes.
