### ISSUE TITLE
Issues with drawing circles

### ISSUE THREAD

**Issue by froebelina** [LibreCAD/LibreCAD#843]
Hello everyone, 

I tried drawing circles and I observed unexpected behavior
### Expected behavior
1. I draw a circle with the Center, Point command, the command input should ask me to enter two points
2. I draw a circle with the Center, Radius command, the command input should ask me for a point and a length
### Observed behavior
1. The command input asks me to enter a point and a radius
2. The command input asks me for a point and afterwards draws the circle without asking me for a radius
### Steps to reproduce or sample file
See above
### Operating System and LibreCAD version info
Windows 7 Pro and same issues on Debian stretch, LibreCAD Version 2.1.3

**Comment by lordofbikes** [comment]
Both tools work as designed. This is a matter of missing or imperfect documentation I think. 
Both issues are discussed in our forum already.

Concerning 1. I agree, that *Specify radius* is a misleading wording. But in fact, the point to specify is the radius of the created circle. One can enter the relative distance e.g. `@50,0` when asked for the radius, what creates a circle with a radius of 50, independent from the center point.
This becomes also clearer by drawing with the mouse, where the mouse click represents the input of a X,Y coordinate. After the center point is set, the circles radius is following the mouse movement.

Concerning 2. you already found out and stated in pr #860 that it works as designed. The problem is the input box for the radius in the tool options bar, which could be overseen or even maybe disabled by mistake. There are several other tools which use input boxes in the tool options bar.

This is not selling bugs as features :wink: 
These tools were not modified significant since QCAD was forked for LibreCAD. See the tool documentation of [QCAD 2.2](http://qcad.org/doc/qcad/2.2/reference/en/chapter19.html#1)
