### ISSUE TITLE
command prompt not working as expected

### ISSUE THREAD

**Issue by ghost** [LibreCAD/LibreCAD#907]
### Expected behavior
pasting the text below in the command prompt should make a drawing:
```
l
100,100
300,100
300,125
280,125
280,170
250,170
250,145
230,145
230,170
180,170
180,200
150,200
150,125
100,125
100,100
z
e
```

### Observed behavior
nothing happened

### Steps to reproduce or sample file
- open LibreCAD
- copy the text mentioned above
- paste it in the command prompt text field
- press enter

### Operating System and LibreCAD version info

Operating System:
GNU/Linux kernel 4.10.0-33 (Ubuntu 17.04)

LibreCAD:
Version: 2.1.2
Compiler: GNU GCC 6.2.0
Compiled on: Sep 17 2016
Qt Version: 5.7.1
Boost Version: 1.62.0

**Comment by lordofbikes** [comment]
This behavior is by design, the expected work flow is not implemented.

Starting with version 2.1.2 the command line has a button on the right side, to open the command line menu.
![grafik](https://user-images.githubusercontent.com/386273/47219258-a2914600-d3ae-11e8-9e0e-fcfab0ba3ce7.png)

Use _Paste Multiple Commands_ and see the above text pasted like this:
`l;100,100;300,100;300,125;280,125;280,170;250,170;250,145;230,145;230,170;180,170;180,200;150,200;150,125;100,125;100,100;z;e;`
Then press ENTER.

Another option is to save the commands in the above format into a text file and run it with _Load Comamnd File_ from this menu.
