### ISSUE TITLE
Trimming line does not un-highlight after done trimming

### ISSUE THREAD

**Issue by charmedrabbit** [LibreCAD/LibreCAD#974]
### Expected behavior
When finished trimming a line (e.g., pressing ESC), the trimming line should un-highlight.

### Observed behavior
After completing a trimming operation, the trimming line does not un-hilight until you zoom.

### Steps to reproduce or sample file
1. Draw 2 intersecting lines
2. Type 'tm' to trim
3. Select one of the lines as the trimming line
4. Click the other line to trim
5. Press 'esc' to get out of trim operation
Result: trimming line is still highlighted green.

### Operating System and LibreCAD version info
Self-compiled MacOS build:
Version: 2.2.0-rc1-14-g0559d309
Compiler: Clang 9.1.0
Compiled on: Apr 8 2018
Qt Version: 5.10.1
Boost Version: 1.65.1
System: macOS High Sierra (10.13)

Incidentally, there are 2 places to post bugs for LibreCAD--here on Github and also on Sourceforge. This is confusing, because it is not clear which one is in active use.

**Comment by shangke1988** [comment]
I meet the same bug. And I meet another similar bug. 

### Expected behavior
When finished a orthogonal  line , the first line should un-highlight.

### Observed behavior
After completing a orthogonal line operation, the first line does not un-highlight, even you zoom, until save and close, open again.

### Steps to reproduce or sample file
1. Draw a line
2. Type 'ortho' to draw a orthogonal   line
3. Click the anywhere
4. Press 'esc' to get out of orthogonal operation
5. Result: the first line is still highlight deep green.

### Operating System and LibreCAD version info
Version: 2.2.0-rc1
Compiler: GNU GCC 4.9.1
Compiled on: Feb 16 2018
Qt Version: 5.4.1
Boost Version: 1.53.0
System: Windows 8.1
